[project]
name = "penguins-project"
version = "0.1.0"
dependencies = [
    "xgboost>=2.1.1",
    "pandas>=2.2.3",
    "scikit-learn>=1.5.2",
    "seaborn>=0.13.2"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
